/**
    # Evance UI Icons
    
    Auto-generated by "gen:icons" based on SVGs found in the './glyph' directory.
    Do NOT edit this file, it will be overwritten.
*/
export { default as AmazonIcon } from "./glyph/AmazonIcon.svg";
export { default as AppleIcon } from "./glyph/AppleIcon.svg";
export { default as BehanceIcon } from "./glyph/BehanceIcon.svg";
export { default as BitbucketIcon } from "./glyph/BitbucketIcon.svg";
export { default as DiscordIcon } from "./glyph/DiscordIcon.svg";
export { default as DribbbleIcon } from "./glyph/DribbbleIcon.svg";
export { default as FacebookIcon } from "./glyph/FacebookIcon.svg";
export { default as FlickrIcon } from "./glyph/FlickrIcon.svg";
export { default as GitHubIcon } from "./glyph/GitHubIcon.svg";
export { default as GoogleIcon } from "./glyph/GoogleIcon.svg";
export { default as HubSpotIcon } from "./glyph/HubSpotIcon.svg";
export { default as InstagramIcon } from "./glyph/InstagramIcon.svg";
export { default as LinkedInIcon } from "./glyph/LinkedInIcon.svg";
export { default as MessengerIcon } from "./glyph/MessengerIcon.svg";
export { default as PayPalIcon } from "./glyph/PayPalIcon.svg";
export { default as PinterestIcon } from "./glyph/PinterestIcon.svg";
export { default as RedditIcon } from "./glyph/RedditIcon.svg";
export { default as SlackIcon } from "./glyph/SlackIcon.svg";
export { default as TikTokIcon } from "./glyph/TikTokIcon.svg";
export { default as TwitchIcon } from "./glyph/TwitchIcon.svg";
export { default as TwitterIcon } from "./glyph/TwitterIcon.svg";
export { default as VimeoIcon } from "./glyph/VimeoIcon.svg";
export { default as WeChatIcon } from "./glyph/WeChatIcon.svg";
export { default as WhatsAppIcon } from "./glyph/WhatsAppIcon.svg";
export { default as XIcon } from "./glyph/XIcon.svg";
export { default as YouTubeIcon } from "./glyph/YouTubeIcon.svg";